/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import core.listeners.CommandListener;
import core.listeners.ReadyListener;
import io.github.cdimascio.dotenv.Dotenv;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.interactions.commands.build.Commands;

public class Bot {

  public static void main(String[] args) {
    Dotenv dotenv = Dotenv.configure().directory("../").load();
    String token = dotenv.get("DISCORD_BOT_TOKEN");

    if(token == null) {
      System.out.println("DISCORD_BOT_TOKEN not set");
      System.exit(1);
    }

    JDA jda = JDABuilder.createDefault(token)
        .addEventListeners(new ReadyListener())
        .addEventListeners(new CommandListener())
        .build();

    jda.updateCommands().addCommands(
        Commands.slash("ping", "Calculate ping of the bot")).queue();
  }
}
